name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: add local pip bin dir to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install requirements
      run: pip3 install setuptools wheel
    - name: install linters
      run: pip3 install -U black flake8
    - name: Run black
      run: black --check --diff .
    - name: Run flake8
      run: flake8 .
