name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    env:
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password

    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: add local pip bin dir to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install requirements
      run: pip3 install setuptools wheel
    - name: run tests
      run: python3 setup.py test
