name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: add local pip bin dir to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install requirements
      run: pip3 install setuptools wheel
    - name: run tests
      run: python3 setup.py test
